### ISSUE TITLE
Unable to start at/stop before rule with filter

### ISSUE THREAD

**Issue by Mardikhouran** [def-gthill/lexurgy-web#2]
The drop-down lists for the options `Start At Rule` and `Stop Before Rule` include the filter in the name of rules, which causes the app to not recognize it.
With this .lsc:
```
Class vowel {a, i, u}
Class cons {p, t, k, x}

vowel-rule:
 a => u / k _

neutralisation @cons:
 [] => x / _

vowel-change:
 a => i / x _
```
The following error message is printed when selecting `neutralisation @cons` for `Start At Rule`:
```
Can't start at rule neutralisation @cons; there is no rule with that name
```
Same for `Stop Before Rule`.

**Comment by def-gthill** [comment]
This is fixed in commit 158aea18ee43276f3d1e6b770d71f08e677c006d and live on the web app. Thanks for reporting!
