### ISSUE TITLE
[New UI/Suggestion] "Trace All" checkbox

### ISSUE THREAD

**Issue by bigyihsuan** [def-gthill/lexurgy-web#4]
I would like a "Trace All" checkbox in the new UI that would select/deselect all words in the word list to trace. I'm working with pretty large word lists, and it is a pain to click every single word.

![image](https://github.com/def-gthill/lexurgy-web/assets/12767476/528615aa-4fc5-4011-af46-b29fe4b4b535)

**Comment by def-gthill** [comment]
Can you explain what you're doing with the trace output? Tracing is really meant for troubleshooting if a few words don't look right. With more information about your use case I can see if there's a better way to support it.

**Comment by bigyihsuan** [comment]
I want to use the trace output to see roughly what rules are/are not affecting words. It's also interesting to see how the words change with each rule.

Pretty much I want to see that _all_ words look right, without needing to change the input word list.

**Comment by def-gthill** [comment]
Makes sense to me. I've put it in the backlog.

**Comment by def-gthill** [comment]
This is now implemented.
